"use client";

import { memo, useState, useCallback, useEffect, useRef } from "react";
import { type NodeProps } from "@xyflow/react";
import { SmartHandles } from "../smart-handles";
import { ChevronDown, Send, X, Loader2, Image } from "lucide-react";

export interface AIPromptNodeData {
  sourceNodeId: string;
  sourceImageUrl: string;
  sourceFileName: string;
  // Auto-generation support: when both are set the node enhances + submits on mount
  initialPrompt?: string;
  autoGenerate?: boolean;
  autoGenerateDelay?: number; // ms to wait before starting auto-generate (stagger concurrent nodes)
}

const ASPECT_RATIOS = [
  { label: "1:1", value: "1:1", width: 1024, height: 1024 },
  { label: "16:9", value: "16:9", width: 1024, height: 576 },
  { label: "9:16", value: "9:16", width: 576, height: 1024 },
  { label: "4:3", value: "4:3", width: 1024, height: 768 },
  { label: "3:4", value: "3:4", width: 768, height: 1024 },
  { label: "21:9", value: "21:9", width: 1024, height: 440 },
];

const VARIATION_OPTIONS = [1, 2, 3, 4];

const SUGGESTIONS = [
  "Put this on a billboard in Times Square",
  "Show this on a laptop screen in a coffee shop",
  "Display on a phone mockup with hands holding it",
  "Place on a magazine cover",
  "Show as a poster on a city wall",
];

function AIPromptNodeComponent({ id, data }: NodeProps) {
  const nodeData = data as AIPromptNodeData;
  const [prompt, setPrompt] = useState(nodeData.initialPrompt ?? "");
  const [aspectRatio, setAspectRatio] = useState("16:9");
  const [variations, setVariations] = useState(2);
  const [showRatioDropdown, setShowRatioDropdown] = useState(false);
  const [showVariationsDropdown, setShowVariationsDropdown] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isEnhancing, setIsEnhancing] = useState(false);
  const [enhanced, setEnhanced] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const autoStartedRef = useRef(false);

  const placeholderSuggestion = SUGGESTIONS[Math.floor(Math.random() * SUGGESTIONS.length)];

  const submitGenerate = useCallback(async (promptText: string) => {
    if (!promptText.trim() || isGenerating) return;
    setIsGenerating(true);
    setError(null);

    try {
      const response = await fetch("/api/ai/generate-mockup", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: promptText.trim(),
          sourceImageUrl: nodeData.sourceImageUrl,
          count: variations,
          aspectRatio,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || `Generation failed: ${response.status}`);
      }

      const result = await response.json();

      if (result.images && result.images.length > 0) {
        const mockups = result.images.map((img: { url?: string; base64?: string; mediaType?: string }, index: number) => ({
          imageUrl: img.url || `data:${img.mediaType};base64,${img.base64}`,
          name: `${nodeData.sourceFileName} - ${promptText.slice(0, 25)}${promptText.length > 25 ? "..." : ""} (${index + 1})`,
        }));

        window.dispatchEvent(new CustomEvent("atlas:mockups-generated", {
          detail: {
            promptNodeId: id,
            sourceNodeId: nodeData.sourceNodeId,
            mockups,
            prompt: promptText,
          },
        }));
      } else {
        setError("No images were generated");
        setIsGenerating(false);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Generation failed");
      setIsGenerating(false);
    }
  }, [isGenerating, nodeData, variations, aspectRatio, id]);

  const handleGenerate = useCallback(() => {
    submitGenerate(prompt);
  }, [prompt, submitGenerate]);

  const handleEnhancePrompt = useCallback(async () => {
    if (!prompt.trim() || isEnhancing || isGenerating) return;
    setIsEnhancing(true);
    setError(null);
    setEnhanced(false);
    try {
      const response = await fetch("/api/ai/enhance-prompt", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim() }),
      });
      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error || "Enhancement failed");
      }
      const { enhancedPrompt } = await response.json();
      setPrompt(enhancedPrompt);
      setEnhanced(true);
      setTimeout(() => setEnhanced(false), 2500);
      return enhancedPrompt as string;
    } catch (err) {
      setError(err instanceof Error ? err.message : "Enhancement failed");
      return null;
    } finally {
      setIsEnhancing(false);
    }
  }, [prompt, isEnhancing, isGenerating]);

  // Auto-generate on mount when the framework stamps out pre-filled prompt nodes
  useEffect(() => {
    if (!nodeData.autoGenerate || !nodeData.initialPrompt || autoStartedRef.current) return;
    autoStartedRef.current = true;

    const run = async () => {
      // Staggered delay: base render time + per-node offset to avoid rate limits
      const delay = 600 + (nodeData.autoGenerateDelay ?? 0);
      await new Promise((r) => setTimeout(r, delay));

      // Enhance with Sage first
      let finalPrompt = nodeData.initialPrompt!;
      try {
        setIsEnhancing(true);
        const res = await fetch("/api/ai/enhance-prompt", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt: finalPrompt }),
        });
        if (res.ok) {
          const { enhancedPrompt } = await res.json();
          finalPrompt = enhancedPrompt;
          setPrompt(enhancedPrompt);
          setEnhanced(true);
          setTimeout(() => setEnhanced(false), 2500);
        }
      } catch {
        // Use original prompt on failure
      } finally {
        setIsEnhancing(false);
      }

      // Then submit to Flux
      await submitGenerate(finalPrompt);
    };

    run();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleGenerate();
    }
  };

  return (
    <div
      className="rounded-xl overflow-hidden"
      style={{
        backgroundColor: "#1a1a1a",
        border: "1px solid #333",
        width: 380,
        boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
      }}
    >
      <SmartHandles nodeId={id} />

      {/* Header Toolbar */}
      <div
        className="flex items-center justify-between px-3 py-2"
        style={{ borderBottom: "1px solid #333" }}
      >
        <div className="flex items-center gap-2">
          {/* Aspect Ratio Selector */}
          <div className="relative">
            <button
              onClick={() => {
                setShowRatioDropdown(!showRatioDropdown);
                setShowVariationsDropdown(false);
              }}
              className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-sm font-medium transition-colors hover:bg-white/10"
              style={{ backgroundColor: "#2a2a2a", color: "#fff" }}
            >
              <span>{aspectRatio}</span>
              <ChevronDown className="w-3 h-3 opacity-60" />
            </button>

            {showRatioDropdown && (
              <div
                className="absolute top-full left-0 mt-1 py-1 rounded-lg z-50"
                style={{ backgroundColor: "#2a2a2a", border: "1px solid #444", minWidth: 80 }}
              >
                {ASPECT_RATIOS.map((ratio) => (
                  <button
                    key={ratio.value}
                    onClick={() => { setAspectRatio(ratio.value); setShowRatioDropdown(false); }}
                    className="w-full px-3 py-1.5 text-left text-sm hover:bg-white/10 transition-colors"
                    style={{ color: ratio.value === aspectRatio ? "#F0FE00" : "#fff" }}
                  >
                    {ratio.label}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Variations Selector */}
          <div className="relative">
            <button
              onClick={() => {
                setShowVariationsDropdown(!showVariationsDropdown);
                setShowRatioDropdown(false);
              }}
              className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-sm font-medium transition-colors hover:bg-white/10"
              style={{ backgroundColor: "#2a2a2a", color: "#fff" }}
            >
              <Image className="w-3.5 h-3.5" />
              <span>{variations}</span>
              <ChevronDown className="w-3 h-3 opacity-60" />
            </button>

            {showVariationsDropdown && (
              <div
                className="absolute top-full left-0 mt-1 py-1 rounded-lg z-50"
                style={{ backgroundColor: "#2a2a2a", border: "1px solid #444", minWidth: 100 }}
              >
                {VARIATION_OPTIONS.map((num) => (
                  <button
                    key={num}
                    onClick={() => { setVariations(num); setShowVariationsDropdown(false); }}
                    className="w-full px-3 py-1.5 text-left text-sm hover:bg-white/10 transition-colors"
                    style={{ color: num === variations ? "#F0FE00" : "#fff" }}
                  >
                    {num} {num === 1 ? "image" : "images"}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Close button */}
        <button
          onClick={() => {
            window.dispatchEvent(new CustomEvent("atlas:close-ai-prompt", {
              detail: { sourceNodeId: nodeData.sourceNodeId },
            }));
          }}
          className="p-1.5 rounded-lg hover:bg-white/10 transition-colors"
          style={{ color: "#888" }}
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Label */}
      <div
        className="flex items-center gap-2 px-3 py-2"
        style={{ borderBottom: "1px solid #2a2a2a" }}
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#888" strokeWidth="2">
          <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
          <circle cx="8.5" cy="8.5" r="1.5" />
          <polyline points="21 15 16 10 5 21" />
        </svg>
        <span className="text-sm" style={{ color: "#888" }}>
          {isGenerating ? "Generating…" : isEnhancing ? "Sage is enhancing…" : `Generate from ${nodeData.sourceFileName}`}
        </span>
        {(isGenerating || isEnhancing) && (
          <Loader2 className="w-3.5 h-3.5 ml-auto animate-spin" style={{ color: "#F0FE00" }} />
        )}
      </div>

      {/* Text Input Area */}
      <div className="p-3">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder={`Try "${placeholderSuggestion}"`}
          className="w-full resize-none text-sm focus:outline-none"
          style={{
            backgroundColor: "transparent",
            color: "#fff",
            minHeight: 120,
            fontFamily: "system-ui, Inter, sans-serif",
          }}
          disabled={isGenerating || isEnhancing}
        />

        {error && (
          <p className="text-xs mt-2" style={{ color: "#ef4444" }}>
            {error}
          </p>
        )}
      </div>

      {/* Bottom Bar */}
      <div
        className="flex items-center justify-between px-3 py-2"
        style={{ borderTop: "1px solid #2a2a2a" }}
      >
        {/* Source thumbnail */}
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded overflow-hidden" style={{ backgroundColor: "#2a2a2a" }}>
            {nodeData.sourceImageUrl && (
              <img src={nodeData.sourceImageUrl} alt="Source" className="w-full h-full object-cover" />
            )}
          </div>
          <span className="text-xs" style={{ color: "#666" }}>
            {nodeData.sourceFileName}
          </span>
        </div>

        {/* Sage enhance button */}
        <button
          type="button"
          onClick={handleEnhancePrompt}
          disabled={!prompt.trim() || isEnhancing || isGenerating}
          title="Enhance with Sage"
          className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium transition-all"
          style={{
            backgroundColor: enhanced ? "#F0FE00" : "#2a2a2a",
            color: enhanced ? "#121212" : prompt.trim() && !isEnhancing && !isGenerating ? "#F0FE00" : "#555",
            border: `1px solid ${enhanced ? "#F0FE00" : prompt.trim() && !isEnhancing && !isGenerating ? "#F0FE0044" : "#333"}`,
            cursor: prompt.trim() && !isEnhancing && !isGenerating ? "pointer" : "not-allowed",
          }}
        >
          {isEnhancing ? (
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
          ) : (
            // eslint-disable-next-line @next/next/no-img-element
            <img src="/sage-logo.svg" alt="Sage" style={{ width: 14, height: 14 }} />
          )}
          <span>{enhanced ? "Enhanced!" : "Sage"}</span>
        </button>

        {/* Generate button */}
        <button
          onClick={handleGenerate}
          disabled={!prompt.trim() || isGenerating || isEnhancing}
          className="w-9 h-9 rounded-full flex items-center justify-center transition-all"
          style={{
            backgroundColor: prompt.trim() && !isGenerating && !isEnhancing ? "#fff" : "#333",
            color: prompt.trim() && !isGenerating && !isEnhancing ? "#000" : "#666",
            cursor: prompt.trim() && !isGenerating && !isEnhancing ? "pointer" : "not-allowed",
          }}
        >
          {isGenerating ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Send className="w-4 h-4" style={{ transform: "rotate(-45deg)" }} />
          )}
        </button>
      </div>
    </div>
  );
}

export const AIPromptNode = memo(AIPromptNodeComponent);
